/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define ENABLE_PPE_SUPPORT  1

#define GETTEXT_PACKAGE "gst-plugins-vvas-2.0"

#define GST_LICENSE "proprietary"

#define HAVE_DLFCN_H 1

#define HAVE_STDIO_H 1

#define LIBDIR "/usr/lib"

#define LOCALEDIR "/usr/share/locale"

#define PACKAGE "gst-plugins-vvas"

#define PACKAGE_BUGREPORT "https://github.com/Xilinx/VVAS/issues"

#define PACKAGE_NAME "GStreamer VVAS Plug-ins"

#define PACKAGE_VERSION "1.18.5"

#define VERSION "1.18.5"

#define VVAS_API_VERSION "2.0"

#define XLNX_EMBEDDED_PLATFORM  1

